### PR TITLE
Added Galaxy Logic Game

### PR DESCRIPTION
**Pull request by RostislavLitovkin**
### .NET MAUI Beautiful UI Challenge (August 2022)

If you're submitting this during August 2022, you can enter in the [.NET MAUI Beautiful UI Challenge](https://aka.ms/maui/uichallenge)! After submitting your pull request, grab the URL and fill out the quick form at https://www.surveymonkey.com/r/maui-ui-challenge to let us know where to send your stickers!

### CODE REVIEW

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Hi @RostislavLitovkin, thanks for your contribution!.  You only have to add the information of the App, description, image, supported platforms etc in the README not all the code. Could you create a personal repository with the code and add the reference here? Thanks!

**Comment by RostislavLitovkin** [comment]
By reference, do you mean just a link to the personal repo?, or is there a better way to do it? Thx for help and feedback! Od: Javier SuárezOdesláno:29 August 2022 09:40Komu: jsuarezruiz/dotnet-maui-showcaseKopie: Rostislav Litovkin; MentionPředmět: Re: [jsuarezruiz/dotnet-maui-showcase] Added Galaxy Logic Game (PR ***@***.*** requested changes on this pull request.Hi @RostislavLitovkin, thanks for your contribution!. You only have to add the information of the App, description, image, supported platforms etc in the README not all the code. Could you create a personal repository with the code and add the reference here? Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by jsuarezruiz** [comment]
> By reference, do you mean just a link to the personal repo?, or is there a better way to do it? Thx for help and feedback! Od: Javier SuárezOdesláno:29 August 2022 09:40Komu: jsuarezruiz/dotnet-maui-showcaseKopie: Rostislav Litovkin; MentionPředmět: Re: [jsuarezruiz/dotnet-maui-showcase] Added Galaxy Logic Game (PR ***@***.*** requested changes on this pull request.Hi @RostislavLitovkin, thanks for your contribution!. You only have to add the information of the App, description, image, supported platforms etc in the README not all the code. Could you create a personal repository with the code and add the reference here? Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Only something like https://github.com/jsuarezruiz/dotnet-maui-showcase/pull/7/files

**Comment by jsuarezruiz** [comment]
Closing due to inactivity.

**Pull request closed without merging**
