### PR TITLE
[.NET MAUI Beautiful UI Challenge] Band Tracker

### PR DESCRIPTION
**Pull request by michaldivis**
Added Band Tracker app.

android_preview

### CODE REVIEW

**Comment by opcodewriter** [comment]
On Windows, I cannot compile the code from https://github.com/michaldivis/band-tracker-app it shows me a lot of compilation errors.
Is the repo up to date?
Thanks

**Comment by michaldivis** [comment]
@opcodewriter the app is doesn't support Windows as of today. The only reason is that the DevExpress components I've used in the app (`FilterChipGroup`) only support iOS and Android. This may change in the future.

**Comment by opcodewriter** [comment]
@michaldivis Thanks, but I want I meant was I cannot **compile** it, not running it on Windows.

**Comment by michaldivis** [comment]
@opcodewriter I have been getting a few compile errors, however, when I try to run the app (instead of just compiling) it works. I've been experiencing this strange behaviour in multiple apps built with MAUI so far. But ultimately, it runs on my PC.

**Pull request merged**
