### PR TITLE
Added - Learn.MauiPaymentUi

### PR DESCRIPTION
**Pull request by DamianSuess**
Added Learn.MauiPaymentUI sample app.

Uses Prism.Maui's Navigation Service and Dependency Injection, as well as, behaviors, dynamic styling, and shared PNG resources.

SampleCards

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
@DamianSuess Could you fix the conflict?. Thanks.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
@DamianSuess Could you fix the conflict?. Thanks.

**Comment by DamianSuess** [comment]
Odd, thi

**Comment by DamianSuess** [comment]
@jsuarezruiz, all sync'd up & should be good to go, sir

**Review by jsuarezruiz — APPROVED** [review]

**Pull request merged**
